### ISSUE TITLE
I'll fix it later.

### ISSUE THREAD

**Issue by MASMC** [MASMC/YTDtR_Bot#1]
ef8f93f1442229800668910e1c2607cb164f1881

issue in globals.js

appveyor log

```
echo "Minimal test:"
"Minimal test:"
node YTDtR.js -tl
C:\projects\ytdtr-bot\src\globals.js:46
module.exports = globals;
      ^
SyntaxError: Unexpected token .
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:694:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
Command exited with code 1
```

**Comment by MASMC** [comment]
If you have any ideas as to why this is happening, feel free to suggest stuff and/or make PRs. Don't expect PRs to be accepted, because of licensing, but I will take into account any made when fixing this issue.

**Comment by MASMC** [comment]
Fixed. I just threw stuff into a function and made the constructor call it.
